import { useState, type ReactNode } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import type { RivalryAnalysis as RivalryAnalysisType } from "../../types";

type Props = { analysis: RivalryAnalysisType };
function Section({ title, note, children }: { title: string; note?: string; children: ReactNode }) {
  return <section className="border-b border-trinetra-border py-8"><div className="mb-5 flex flex-col gap-2 md:flex-row md:items-baseline md:justify-between"><h2 className="font-display text-2xl text-neutral-100">{title}</h2>{note && <p className="max-w-2xl text-sm leading-6 text-neutral-500">{note}</p>}</div>{children}</section>;
}
function Empty({ children }: { children: ReactNode }) { return <p className="border-l border-trinetra-border py-2 pl-4 text-sm leading-6 text-neutral-500">INSUFFICIENT VERIFIED PUBLIC DATA <span className="block normal-case text-neutral-600">{children}</span></p>; }
function Value({ metric }: { metric: { value: unknown; source?: string; year?: unknown } }) { return <div className="text-right"><p className="text-lg text-neutral-100">{metric.value == null || metric.value === "" ? "Not available" : String(metric.value)}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-neutral-600">{metric.source || "Dataset source unavailable"}{metric.year ? ` · ${metric.year}` : ""}</p></div>; }
function BulletList({ items, empty }: { items?: unknown[]; empty: string }) { return items?.length ? <ul className="flex flex-col gap-3">{items.map((item, index) => <li key={`${String(item)}-${index}`} className="border-b border-trinetra-border/70 pb-3 text-sm leading-6 text-neutral-300 last:border-0">{typeof item === "string" ? item : JSON.stringify(item)}</li>)}</ul> : <Empty>{empty}</Empty>; }

export default function AnalysisResults({ analysis }: Props) {
  const [tab, setTab] = useState("Overview");
  const [open, setOpen] = useState<string | null>(null);
  const a = analysis.country_a;
  const b = analysis.country_b;
  const profileA = analysis.country_a_profile;
  const profileB = analysis.country_b_profile;
  const sourceMeta = (profile: typeof profileA) => profile?._meta?.source || "Country profile dataset";
  const metric = (value: unknown, source: string, year?: unknown) => ({ value, source, year: year || profileA?._meta?.last_updated?.slice(0, 4) });
  const tabs = ["Overview", "Economy", "Military", "Energy", "Geography", "Maritime", "Technology", "Trade", "Relationships", "Dependencies", "Vulnerabilities", "Foreign Policy", "Chokepoints", "Strategic Assets", "Timeline"];
  const metrics = [
    ["Population", metric(profileA?.demographics?.population_millions ? `${profileA.demographics.population_millions}M` : null, sourceMeta(profileA), "2024"), metric(profileB?.demographics?.population_millions ? `${profileB.demographics.population_millions}M` : null, sourceMeta(profileB), "2024")],
    ["GDP", metric(profileA?.economy?.gdp_usd_trillion ? `$${profileA.economy.gdp_usd_trillion}T` : null, sourceMeta(profileA), "2025"), metric(profileB?.economy?.gdp_usd_trillion ? `$${profileB.economy.gdp_usd_trillion}T` : null, sourceMeta(profileB), "2025")],
    ["GDP growth", metric(profileA?.economy?.gdp_growth_pct != null ? `${profileA.economy.gdp_growth_pct}%` : null, sourceMeta(profileA), "2025"), metric(profileB?.economy?.gdp_growth_pct != null ? `${profileB.economy.gdp_growth_pct}%` : null, sourceMeta(profileB), "2025")],
    ["Defence expenditure", metric(profileA?.military?.defence_spending_usd_billion ? `$${profileA.military.defence_spending_usd_billion}B` : null, profileA?.military?.defence_spending_pct_gdp_source || sourceMeta(profileA), "2024"), metric(profileB?.military?.defence_spending_usd_billion ? `$${profileB.military.defence_spending_usd_billion}B` : null, profileB?.military?.defence_spending_pct_gdp_source || sourceMeta(profileB), "2024")],
    ["Active personnel", metric(profileA?.military?.active_troops?.toLocaleString(), sourceMeta(profileA), "2025"), metric(profileB?.military?.active_troops?.toLocaleString(), sourceMeta(profileB), "2025")],
    ["Nuclear status", metric(profileA?.nuclear?.weapons_state ? "Weapons state" : "Not stated", sourceMeta(profileA), "2026"), metric(profileB?.nuclear?.weapons_state ? "Weapons state" : "Not stated", sourceMeta(profileB), "2026")],
  ];
  const positions = analysis.deep_dive_analyses?.filter((item) => item.assessment || item.facts).slice(0, 4) || [];
  const chokepoints = analysis.comparison_data?.chokepoints || analysis.chokepoints?.relevant_chokepoints || [];
  const pairModules = analysis.comparison_data?.pair_modules || [];
  const availability = analysis.comparison_data?.availability || {};
  return <div className="overflow-hidden rounded border border-trinetra-border bg-trinetra-panel/20">
    <div className="border-b border-trinetra-border p-5 md:p-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><div><p className="eyebrow mb-3">COUNTRY A</p><h2 className="font-display text-3xl text-neutral-100">{a.name}</h2><p className="mt-1 font-mono text-xs text-neutral-500">{a.id} · strategic profile</p></div><div className="text-center font-display text-4xl text-trinetra-saffron">VS</div><div className="lg:text-right"><p className="eyebrow mb-3">COUNTRY B</p><h2 className="font-display text-3xl text-neutral-100">{b.name}</h2><p className="mt-1 font-mono text-xs text-neutral-500">{b.id} · strategic profile</p></div></div><div className="mt-7 grid grid-cols-2 gap-px border border-trinetra-border bg-trinetra-border md:grid-cols-3 xl:grid-cols-6">{metrics.map(([label, av, bv]) => <div key={String(label)} className="bg-trinetra-bg px-4 py-4"><p className="data-meta">{String(label)}</p><div className="mt-3 flex items-end justify-between gap-3"><Value metric={av as { value: unknown; source?: string; year?: unknown }} /><span className="text-xs text-trinetra-saffron">/</span><Value metric={bv as { value: unknown; source?: string; year?: unknown }} /></div><div className="mt-2 flex justify-between font-mono text-[10px] text-neutral-600"><span>{a.id}</span><span>{b.id}</span></div></div>)}</div></div>
    <nav aria-label="Comparison categories" className="flex gap-1 overflow-x-auto border-b border-trinetra-border px-4 py-3">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap px-3 py-2 text-xs transition-colors ${tab === item ? "border-b border-trinetra-saffron text-trinetra-saffron" : "text-neutral-500 hover:text-neutral-200"}`}>{item}</button>)}</nav>
    <div className="px-5 md:px-7">{tab === "Overview" ? <>
      <Section title="Structural differences" note="Factual comparison only. No composite score or winner logic."><div className="grid gap-7 md:grid-cols-2"><div><p className="eyebrow mb-3 text-trinetra-saffron">{a.name}</p><BulletList items={[...(analysis.military?.country_a?.strengths || [])].slice(0, 5)} empty="No structural strengths are recorded." /></div><div><p className="eyebrow mb-3 text-trinetra-saffron">{b.name}</p><BulletList items={[...(analysis.military?.country_b?.strengths || [])].slice(0, 5)} empty="No structural strengths are recorded." /></div></div></Section>
      <Section title="Strategic position" note={analysis.geopolitical?.note || "Position statements require source-backed context."}><div className="grid gap-7 md:grid-cols-2"><div><p className="eyebrow mb-3">{a.id} · POSITION</p><p className="text-sm leading-7 text-neutral-300">{analysis.deep_dive_analyses?.[0]?.assessment?.statement || "Public evidence is insufficient to state a pair-specific position here."}</p></div><div><p className="eyebrow mb-3">{b.id} · POSITION</p><p className="text-sm leading-7 text-neutral-300">{analysis.deep_dive_analyses?.[1]?.assessment?.statement || "Public evidence is insufficient to state a pair-specific position here."}</p></div></div></Section>
      <Section title="Leverage and constraints"><div className="grid gap-7 md:grid-cols-2"><div><p className="eyebrow mb-3 text-trinetra-saffron">{a.name} · LEVERAGE</p><BulletList items={analysis.military?.country_a?.strengths} empty="No leverage points are recorded." /></div><div><p className="eyebrow mb-3 text-trinetra-saffron">{b.name} · LEVERAGE</p><BulletList items={analysis.military?.country_b?.strengths} empty="No leverage points are recorded." /></div></div></Section>
      <Section title="External actor assessment" note="Possible roles are assessments, not deterministic predictions."><BulletList items={analysis.geopolitical?.external_actors?.map((actor) => `${actor.country} · ${actor.role}: ${actor.reason}`)} empty={availability.external_actor_records ? "No third-party assessment is available for this pair." : "The external-actor dataset is not available for this pair."} /></Section>
      <Section title="Trinetra assessment" note="Accuracy means stating real advantages clearly while preserving constraints."><div className="border-l border-trinetra-saffron pl-5 text-sm leading-7 text-neutral-300">{analysis.ai_summary || "The current evidence set does not provide a synthesized bottom line. Review the factual metrics, relationship records, chokepoints and source classifications above."}</div><p className="mt-5 font-mono text-[10px] uppercase tracking-wider text-neutral-600">Assessment · not a forecast · no winner assigned</p></Section>
    </> : <Section title={`${tab} assessment`} note="Focused workspace. Values and statements remain source-dependent."><div className="mb-4 font-mono text-[10px] uppercase tracking-wider text-neutral-600">{pairModules.length ? `${pairModules.length} pair record${pairModules.length === 1 ? "" : "s"} loaded` : `No pair-specific ${tab.toLowerCase()} module loaded`}</div><div className="grid gap-4 md:grid-cols-2"><article className="border border-trinetra-border p-5"><p className="eyebrow mb-4">{a.id}</p><BulletList items={analysis.deep_dive_analyses?.filter((item) => item.subject.toLowerCase().includes(tab.toLowerCase())).flatMap((item) => item.facts?.map((fact) => `${fact.record_type}: ${fact.statement}`) || [])} empty={`No verified ${tab.toLowerCase()} records are available.`} /></article><article className="border border-trinetra-border p-5"><p className="eyebrow mb-4">{b.id}</p><BulletList items={analysis.deep_dive_analyses?.filter((item) => item.subject.toLowerCase().includes(tab.toLowerCase())).flatMap((item) => item.facts?.map((fact) => `${fact.record_type}: ${fact.statement}`) || [])} empty={`No verified ${tab.toLowerCase()} records are available.`} /></article></div>{tab === "Chokepoints" && <div className="mt-6 flex flex-col gap-3">{chokepoints.map((cp) => { const isOpen = open === cp.chokepoint; return <article key={cp.chokepoint} className="border border-trinetra-border"><button onClick={() => setOpen(isOpen ? null : cp.chokepoint)} className="flex w-full items-center justify-between p-4 text-left text-sm text-neutral-200"><span>{cp.chokepoint}</span>{isOpen ? <ChevronDown size={16} /> : <ChevronRight size={16} />}</button>{isOpen && <div className="grid gap-5 border-t border-trinetra-border p-4 text-sm leading-6 text-neutral-400 md:grid-cols-2"><p>{cp.why_it_matters}</p><p>{a.id}: {cp.country_a_leverage?.reason || cp.country_a_exposure?.reason || "Not stated"}<br />{b.id}: {cp.country_b_leverage?.reason || cp.country_b_exposure?.reason || "Not stated"}</p></div>}</article>})}</div>}</Section>}</div>
    <footer className="grid gap-4 border-t border-trinetra-border px-5 py-5 text-xs text-neutral-500 md:grid-cols-3 md:px-7"><p><span className="text-trinetra-saffron">DATA INTEGRITY</span><br />Verified public datasets and institutional sources where available.</p><p><span className="text-trinetra-saffron">EVIDENCE LABELS</span><br />Fact · Estimate · Official Claim · Assessment · Unknown</p><p className="md:text-right"><span className="text-trinetra-saffron">REFERENCE YEARS VARY</span><br />Each metric should be read with its source and reference year.</p></footer>
  </div>;
}
