"""
Generates data/countries/*.json for all 20 Trinetra countries.
Run once: python3 gen_countries.py
All figures are labelled demo/approximate — replace with sourced data later
via data/sources/ + confidence fields.
"""
import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "countries")
os.makedirs(OUT_DIR, exist_ok=True)

# id, name, file, iso3 + core stats (approximate, for demo purposes only)
COUNTRIES = {
    "IND": dict(name="India", file="india.json", region="South Asia",
        pop_m=1441, gdp_tn=3.94, gdp_growth=6.8, mil_spend_bn=86.1, mil_pct_gdp=2.4,
        active_troops=1455000, nuclear=True, energy_import_dep=0.85,
        allies=["RUS", "FRA", "USA-partial"], rivals=["PAK", "CHN"],
        strengths=["Large domestic market", "Growing tech/IT sector", "Demographic dividend", "Strategic Indo-Pacific position"],
        vulnerabilities=["Heavy energy import dependence", "Two-front border tension (China/Pakistan)", "Infrastructure gaps in interior regions"],
        priorities=["Border security vs China/Pakistan", "Energy diversification", "Domestic defence manufacturing (Atmanirbhar)", "Indo-Pacific strategic partnerships"]),
    "CHN": dict(name="China", file="china.json", region="East Asia",
        pop_m=1410, gdp_tn=17.8, gdp_growth=5.0, mil_spend_bn=296, mil_pct_gdp=1.7,
        active_troops=2035000, nuclear=True, energy_import_dep=0.72,
        allies=["RUS", "PAK", "PRK"], rivals=["USA", "IND", "JPN"],
        strengths=["Manufacturing/industrial base", "Global supply chain centrality", "Rapid naval expansion", "Belt & Road strategic reach"],
        vulnerabilities=["Malacca Strait energy chokepoint", "Aging population", "Property-sector debt overhang", "Export dependence on Western markets"],
        priorities=["Taiwan reunification posture", "South China Sea control", "Tech self-sufficiency (semiconductors)", "Belt & Road consolidation"]),
    "USA": dict(name="United States", file="usa.json", region="North America",
        pop_m=335, gdp_tn=27.4, gdp_growth=2.5, mil_spend_bn=916, mil_pct_gdp=3.4,
        active_troops=1328000, nuclear=True, energy_import_dep=-0.05,
        allies=["GBR", "JPN", "AUS", "KOR", "ISR"], rivals=["CHN", "RUS", "IRN"],
        strengths=["Global reserve currency", "Technology/innovation leadership", "Energy self-sufficiency (shale)", "Global alliance network"],
        vulnerabilities=["High national debt", "Political polarization", "Overseas commitment overstretch"],
        priorities=["Indo-Pacific deterrence of China", "Alliance cohesion (NATO/AUKUS)", "Tech export controls", "Domestic semiconductor reshoring"]),
    "RUS": dict(name="Russia", file="russia.json", region="Eurasia",
        pop_m=144, gdp_tn=2.02, gdp_growth=1.5, mil_spend_bn=109, mil_pct_gdp=5.9,
        active_troops=1330000, nuclear=True, energy_import_dep=-1.2,
        allies=["CHN", "PRK", "IRN"], rivals=["USA", "GBR", "FRA"],
        strengths=["Vast energy exports", "Nuclear arsenal parity with US", "Strategic depth/geography"],
        vulnerabilities=["Western sanctions isolation", "Ukraine war attrition", "Technology import restrictions"],
        priorities=["Ukraine war objectives", "Energy leverage over Europe", "Deepening China alignment", "Arctic resource access"]),
    "JPN": dict(name="Japan", file="japan.json", region="East Asia",
        pop_m=123, gdp_tn=4.2, gdp_growth=1.0, mil_spend_bn=51, mil_pct_gdp=1.2,
        active_troops=247000, nuclear=False, energy_import_dep=0.9,
        allies=["USA", "AUS", "GBR"], rivals=["CHN", "PRK"],
        strengths=["Advanced technology/manufacturing", "US alliance backbone", "High-precision defence industry"],
        vulnerabilities=["Near-total energy import dependence", "Aging/shrinking population", "Constitutional limits on offensive military"],
        priorities=["China/Taiwan contingency planning", "Energy import route security", "Defence spending expansion (2% GDP target)"]),
    "DEU": dict(name="Germany", file="germany.json", region="Europe",
        pop_m=84, gdp_tn=4.6, gdp_growth=0.5, mil_spend_bn=68, mil_pct_gdp=1.5,
        active_troops=181000, nuclear=False, energy_import_dep=0.65,
        allies=["FRA", "GBR", "USA"], rivals=["RUS"],
        strengths=["Industrial/manufacturing base", "EU economic leadership", "Export-driven engineering sector"],
        vulnerabilities=["Post-2022 energy supply shock exposure", "Export dependence on China market", "Underinvested military (post-Zeitenwende ramp-up)"],
        priorities=["Military modernisation (Zeitenwende)", "Energy diversification from Russia", "EU strategic autonomy"]),
    "GBR": dict(name="United Kingdom", file="uk.json", region="Europe",
        pop_m=68, gdp_tn=3.5, gdp_growth=0.9, mil_spend_bn=68, mil_pct_gdp=2.3,
        active_troops=138000, nuclear=True, energy_import_dep=0.4,
        allies=["USA", "FRA", "AUS"], rivals=["RUS"],
        strengths=["Nuclear deterrent + UN Security Council seat", "Financial services hub (City of London)", "Global naval reach", "AUKUS partnership"],
        vulnerabilities=["Post-Brexit trade friction with EU", "Shrinking conventional force size", "North Sea energy decline"],
        priorities=["AUKUS submarine program", "NATO Eastern flank support", "Indo-Pacific tilt"]),
    "FRA": dict(name="France", file="france.json", region="Europe",
        pop_m=68, gdp_tn=3.0, gdp_growth=1.0, mil_spend_bn=61, mil_pct_gdp=2.1,
        active_troops=203000, nuclear=True, energy_import_dep=0.35,
        allies=["DEU", "GBR", "USA"], rivals=["RUS"],
        strengths=["Independent nuclear deterrent", "Nuclear power energy self-sufficiency", "African/Indo-Pacific overseas presence", "Domestic defence industry (Dassault, etc.)"],
        vulnerabilities=["Sahel influence decline", "Fiscal deficit constraints", "Domestic political instability"],
        priorities=["Strategic autonomy from US", "Indo-Pacific overseas territories defence", "EU defence-industrial integration"]),
    "KOR": dict(name="South Korea", file="south-korea.json", region="East Asia",
        pop_m=52, gdp_tn=1.87, gdp_growth=2.2, mil_spend_bn=48, mil_pct_gdp=2.6,
        active_troops=555000, nuclear=False, energy_import_dep=0.93,
        allies=["USA", "JPN"], rivals=["PRK", "CHN"],
        strengths=["Advanced semiconductor industry", "Strong US alliance/troop presence", "High-tech defence manufacturing exports"],
        vulnerabilities=["Total energy import dependence", "North Korea artillery range over Seoul", "China trade over-reliance"],
        priorities=["North Korea deterrence", "Semiconductor supply chain security", "US extended deterrence assurance"]),
    "TUR": dict(name="Türkiye", file="turkey.json", region="Middle East/Europe",
        pop_m=86, gdp_tn=1.11, gdp_growth=3.0, mil_spend_bn=15.8, mil_pct_gdp=1.5,
        active_troops=355000, nuclear=False, energy_import_dep=0.7,
        allies=["USA-partial", "AZE"], rivals=["GRC", "SYR-actors"],
        strengths=["NATO's second-largest army", "Domestic drone industry (Bayraktar)", "Bosphorus strait control", "Regional mediator role"],
        vulnerabilities=["Currency/inflation instability", "Kurdish militant border conflicts", "Energy import dependence"],
        priorities=["Syria/Kurdish border security", "Domestic defence industry growth", "Balancing NATO and Russia ties"]),
    "SAU": dict(name="Saudi Arabia", file="saudi-arabia.json", region="Middle East",
        pop_m=36, gdp_tn=1.06, gdp_growth=2.0, mil_spend_bn=75, mil_pct_gdp=7.1,
        active_troops=257000, nuclear=False, energy_import_dep=-1.5,
        allies=["USA", "UAE"], rivals=["IRN"],
        strengths=["Largest global oil reserves/exporter", "High military spending ratio", "Vision 2030 economic diversification drive"],
        vulnerabilities=["Oil price/demand dependence", "Yemen conflict spillover", "Iran proxy threats to oil infrastructure"],
        priorities=["Iran deterrence/normalisation balance", "Yemen conflict resolution", "Oil revenue diversification (Vision 2030)"]),
    "IRN": dict(name="Iran", file="iran.json", region="Middle East",
        pop_m=90, gdp_tn=0.4, gdp_growth=3.0, mil_spend_bn=10.3, mil_pct_gdp=2.6,
        active_troops=610000, nuclear=False, energy_import_dep=-1.8,
        allies=["RUS", "CHN", "proxy-network"], rivals=["ISR", "SAU", "USA"],
        strengths=["Large ballistic missile arsenal", "Regional proxy network (Hezbollah, Houthis)", "Energy reserves despite sanctions"],
        vulnerabilities=["Severe international sanctions", "Domestic economic distress", "Isolated air force/navy modernisation"],
        priorities=["Nuclear program leverage", "Proxy network maintenance", "Sanctions evasion via Russia/China ties"]),
    "ISR": dict(name="Israel", file="israel.json", region="Middle East",
        pop_m=9.8, gdp_tn=0.53, gdp_growth=2.0, mil_spend_bn=27.5, mil_pct_gdp=5.3,
        active_troops=169500, nuclear=True, energy_import_dep=-0.1,
        allies=["USA"], rivals=["IRN", "proxy-actors"],
        strengths=["Advanced defence tech (Iron Dome, cyber)", "Undeclared nuclear deterrent", "Strong US strategic backing"],
        vulnerabilities=["Multi-front proxy threat exposure", "Small strategic depth", "International isolation risk"],
        priorities=["Iran nuclear threat neutralisation", "Multi-front proxy deterrence", "Abraham Accords expansion"]),
    "PAK": dict(name="Pakistan", file="pakistan.json", region="South Asia",
        pop_m=240, gdp_tn=0.34, gdp_growth=2.5, mil_spend_bn=10.2, mil_pct_gdp=2.8,
        active_troops=654000, nuclear=True, energy_import_dep=0.7,
        allies=["CHN"], rivals=["IND"],
        strengths=["Nuclear deterrent vs India", "China strategic partnership (CPEC)", "Large standing army"],
        vulnerabilities=["Chronic economic/debt crisis", "IMF dependency", "Domestic militant insurgencies"],
        priorities=["India deterrence (Kashmir)", "China alignment (CPEC)", "Economic stabilisation via IMF/China"]),
    "AUS": dict(name="Australia", file="australia.json", region="Oceania",
        pop_m=26.6, gdp_tn=1.79, gdp_growth=2.0, mil_spend_bn=32.3, mil_pct_gdp=1.9,
        active_troops=59000, nuclear=False, energy_import_dep=-0.3,
        allies=["USA", "GBR", "JPN"], rivals=["CHN-tensions"],
        strengths=["Resource/energy exporter", "AUKUS submarine partnership", "Stable alliance-anchored posture"],
        vulnerabilities=["Small population/force size", "China trade dependence", "Long supply lines"],
        priorities=["AUKUS submarine acquisition", "Pacific Islands influence competition with China", "Trade diversification from China"]),
    "CAN": dict(name="Canada", file="canada.json", region="North America",
        pop_m=40, gdp_tn=2.14, gdp_growth=1.5, mil_spend_bn=27, mil_pct_gdp=1.3,
        active_troops=68000, nuclear=False, energy_import_dep=-0.6,
        allies=["USA", "GBR", "FRA"], rivals=[],
        strengths=["Energy/resource exporter", "NATO/NORAD integration with US", "Arctic sovereignty presence"],
        vulnerabilities=["Below-NATO-target defence spending", "US economic over-dependence", "Arctic capability gaps"],
        priorities=["NATO spending target compliance", "Arctic sovereignty assertion", "US trade relationship management"]),
    "BRA": dict(name="Brazil", file="brazil.json", region="South America",
        pop_m=216, gdp_tn=2.17, gdp_growth=2.5, mil_spend_bn=22.9, mil_pct_gdp=1.1,
        active_troops=360000, nuclear=False, energy_import_dep=-0.2,
        allies=["ARG", "regional-blocs"], rivals=[],
        strengths=["Largest South American economy", "Agricultural/energy self-sufficiency", "Amazon strategic resource base"],
        vulnerabilities=["Domestic inequality/fiscal strain", "Amazon deforestation international pressure", "Underinvested military modernisation"],
        priorities=["Regional (Mercosur) economic leadership", "Amazon sovereignty vs international pressure", "BRICS strategic alignment"]),
    "IDN": dict(name="Indonesia", file="indonesia.json", region="Southeast Asia",
        pop_m=283, gdp_tn=1.47, gdp_growth=5.0, mil_spend_bn=9.5, mil_pct_gdp=0.7,
        active_troops=400000, nuclear=False, energy_import_dep=0.1,
        allies=["ASEAN-bloc"], rivals=[],
        strengths=["Largest ASEAN economy/population", "Critical maritime chokepoints (Malacca/Sunda)", "Non-aligned strategic positioning"],
        vulnerabilities=["Archipelagic defence complexity", "South China Sea claim overlap with China", "Low defence spending ratio"],
        priorities=["Maritime chokepoint security", "South China Sea claims management", "ASEAN centrality maintenance"]),
    "ITA": dict(name="Italy", file="italy.json", region="Europe",
        pop_m=59, gdp_tn=2.3, gdp_growth=0.7, mil_spend_bn=33, mil_pct_gdp=1.5,
        active_troops=161500, nuclear=False, energy_import_dep=0.75,
        allies=["FRA", "DEU", "USA"], rivals=[],
        strengths=["Mediterranean strategic position", "NATO southern-flank anchor", "Domestic defence industry (Leonardo)"],
        vulnerabilities=["High energy import dependence", "North Africa migration/instability exposure", "High public debt"],
        priorities=["Mediterranean/North Africa stability", "Energy diversification post-Russia", "NATO southern flank commitments"]),
    "ARE": dict(name="United Arab Emirates", file="uae.json", region="Middle East",
        pop_m=9.4, gdp_tn=0.51, gdp_growth=4.0, mil_spend_bn=22, mil_pct_gdp=4.3,
        active_troops=63000, nuclear=False, energy_import_dep=-1.4,
        allies=["SAU", "USA"], rivals=["IRN-tensions"],
        strengths=["Major oil/gas exporter", "Regional logistics/trade hub (Jebel Ali, DP World)", "Advanced diversification (Abraham Accords, tech investment)"],
        vulnerabilities=["Strait of Hormuz exposure", "Small population/force base", "Iran proxy threat exposure"],
        priorities=["Hormuz security", "Economic diversification beyond oil", "Regional mediator/hedging role (Iran-US-China)"]),
}


def build(cid, d):
    return {
        "id": cid,
        "name": d["name"],
        "region": d["region"],
        "demographics": {
            "population_millions": d["pop_m"],
        },
        "economy": {
            "gdp_usd_trillion": d["gdp_tn"],
            "gdp_growth_pct": d["gdp_growth"],
            "notes": "Demo/approximate figures — replace with sourced data via data/sources/",
        },
        "military": {
            "active_troops": d["active_troops"],
            "defence_spending_usd_billion": d["mil_spend_bn"],
            "defence_spending_pct_gdp": d["mil_pct_gdp"],
        },
        "energy": {
            "net_import_dependence_ratio": d["energy_import_dep"],
            "note": "Positive = net importer, negative = net exporter (approximate ratio, demo data)",
        },
        "infrastructure": {},
        "trade": {},
        "technology": {},
        "geography": {"region": d["region"]},
        "politics": {},
        "nuclear": {"weapons_state": d["nuclear"]},
        "strategic_priorities": d["priorities"],
        "dependencies": [],
        "vulnerabilities": d["vulnerabilities"],
        "strengths": d["strengths"],
        "alliances": d["allies"],
        "rivals": d["rivals"],
        "_meta": {"data_quality": "demo", "source": "see data/sources/", "confidence": "low-demo"},
    }


index = {"countries": []}
for cid, d in COUNTRIES.items():
    path = os.path.join(OUT_DIR, d["file"])
    with open(path, "w") as f:
        json.dump(build(cid, d), f, indent=2)
    index["countries"].append({"id": cid, "name": d["name"], "file": d["file"]})

with open(os.path.join(OUT_DIR, "index.json"), "w") as f:
    json.dump(index, f, indent=2)

print(f"Wrote {len(COUNTRIES)} country files + index.json to {OUT_DIR}")
