export const COUNTRY_FLAGS: Record<string, string> = {
  IND: "🇮🇳",
  CHN: "🇨🇳",
  USA: "🇺🇸",
  RUS: "🇷🇺",
  JPN: "🇯🇵",
  DEU: "🇩🇪",
  GBR: "🇬🇧",
  FRA: "🇫🇷",
  KOR: "🇰🇷",
  TUR: "🇹🇷",
  SAU: "🇸🇦",
  IRN: "🇮🇷",
  ISR: "🇮🇱",
  PAK: "🇵🇰",
  AUS: "🇦🇺",
  CAN: "🇨🇦",
  BRA: "🇧🇷",
  ARG: "🇦🇷",
  IDN: "🇮🇩",
  ITA: "🇮🇹",
  ARE: "🇦🇪",
  BGD: "🇧🇩",
  EGY: "🇪🇬",
  ZAF: "🇿🇦",
  MEX: "🇲🇽",
  NGA: "🇳🇬",
  VNM: "🇻🇳",
  PHL: "🇵🇭",
  THA: "🇹🇭",
  MYS: "🇲🇾",
  SGP: "🇸🇬",
  TWN: "🇹🇼",
  UKR: "🇺🇦",
  POL: "🇵🇱",
  SWE: "🇸🇪",
  NOR: "🇳🇴",
  NLD: "🇳🇱",
  CHE: "🇨🇭",
  ESP: "🇪🇸",
  QAT: "🇶🇦",
  KWT: "🇰🇼",
  OMN: "🇴🇲",
  IRQ: "🇮🇶",
  SYR: "🇸🇾",
  PRK: "🇰🇵",
  NZL: "🇳🇿",
  CHL: "🇨🇱",
  COL: "🇨🇴",
  PER: "🇵🇪",
  KAZ: "🇰🇿",
};

export function getCountryFlag(id?: string): string {
  if (!id) return "🌐";
  return COUNTRY_FLAGS[id.toUpperCase()] || "🌐";
}
