import { useMemo, useState } from "react";

interface Node { id: string; label: string; }
interface Edge { source: string; target: string; type: string; }
interface Props { nodes: Node[]; edges: Edge[]; }
const WIDTH = 640; const HEIGHT = 560; const RADIUS = 220; const CENTER = { x: WIDTH / 2, y: HEIGHT / 2 };

export default function GlobalMap({ nodes, edges }: Props) {
  const [filter, setFilter] = useState<"all" | "alliance" | "rivalry">("all");
  const [selected, setSelected] = useState<string | null>(null);
  const positions = useMemo(() => Object.fromEntries(nodes.map((n, i) => { const angle = (2 * Math.PI * i) / Math.max(nodes.length, 1) - Math.PI / 2; return [n.id, { x: CENTER.x + RADIUS * Math.cos(angle), y: CENTER.y + RADIUS * Math.sin(angle) }]; })), [nodes]);
  const visibleEdges = edges.filter((e) => filter === "all" || e.type === filter);
  const activeNode = nodes.find((n) => n.id === selected);
  const activeTies = selected ? visibleEdges.filter((e) => e.source === selected || e.target === selected) : [];
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_240px]">
    <div><div className="mb-4 flex flex-wrap items-center gap-2" role="group" aria-label="Filter relationships">{(["all", "alliance", "rivalry"] as const).map((f) => <button key={f} onClick={() => setFilter(f)} aria-pressed={filter === f} className={`rounded-sm border px-3 py-1.5 text-xs transition-colors ${filter === f ? "border-trinetra-saffron bg-trinetra-saffron text-black" : "border-trinetra-border text-neutral-400 hover:border-neutral-500 hover:text-white"}`}>{f === "all" ? "All ties" : f === "alliance" ? "Alliances only" : "Rivalries only"}</button>)}</div>
      <div className="overflow-hidden border border-trinetra-border bg-trinetra-bg"><svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} className="mx-auto aspect-[640/560] w-full" role="img" aria-label="Geopolitical relationship network">{visibleEdges.map((e, i) => { const a = positions[e.source]; const b = positions[e.target]; if (!a || !b) return null; const active = !selected || e.source === selected || e.target === selected; return <line key={`${e.source}-${e.target}-${i}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={e.type === "rivalry" ? "#f87171" : "#ff9933"} strokeWidth={active && selected ? 2 : 1} opacity={active ? (selected ? .8 : .35) : .08} />; })}{nodes.map((n) => { const p = positions[n.id]; if (!p) return null; const active = selected === n.id; return <g key={n.id} role="button" tabIndex={0} aria-label={`Inspect ${n.label || n.id}`} onClick={() => setSelected(active ? null : n.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelected(active ? null : n.id); }}><circle cx={p.x} cy={p.y} r={active ? 10 : 6} fill={active ? "#ff9933" : "#e5e5e5"} /><text x={p.x} y={p.y - 14} textAnchor="middle" fontSize="11" fill={active ? "#ff9933" : "#a3a3a3"} fontFamily="DM Sans, sans-serif">{n.id}</text></g>; })}</svg></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-neutral-400"><span className="flex items-center gap-2"><span className="h-px w-4 bg-trinetra-saffron" /> Alliance</span><span className="flex items-center gap-2"><span className="h-px w-4 bg-red-400" /> Rivalry</span><span className="text-neutral-500">Select a nation to inspect ties</span></div></div>
    <aside className="border-l border-trinetra-border pl-5" aria-live="polite"><p className="section-kicker">Selection</p>{activeNode ? <><h2 className="mt-4 font-display text-2xl text-white">{activeNode.label || activeNode.id}</h2><p className="data-meta mt-1">{activeNode.id}</p><div className="mt-6 border-t border-trinetra-border pt-4"><p className="data-meta">Visible relationships</p><p className="mt-1 font-display text-3xl text-trinetra-saffron">{activeTies.length}</p>{activeTies.length > 0 && <ul className="mt-4 flex flex-col gap-2 text-xs text-neutral-400">{activeTies.slice(0, 6).map((tie, i) => <li key={`${tie.source}-${tie.target}-${i}`} className="border-b border-trinetra-border pb-2">{tie.source === selected ? tie.target : tie.source}<span className="ml-2 text-neutral-600">{tie.type}</span></li>)}</ul>}</div></> : <p className="mt-4 text-sm leading-6 text-neutral-400">Select a nation to focus its visible alliances and rivalries.</p>}</aside>
  </div>;
}
