import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, CircleAlert, RefreshCw } from "lucide-react";
import Header from "../components/dashboard/Header";
import Footer from "../components/dashboard/Footer";
import GlobalMap from "../components/network/GlobalMap";
import { api } from "../services/api";

interface NetworkData { nodes: { id: string; label: string }[]; edges: { source: string; target: string; type: string }[]; }
const framework = [["01", "GEOGRAPHY", "Where physical position creates strategic advantage."], ["02", "CAPABILITY", "What a state can actually do."], ["03", "RELATIONSHIPS", "Who affects whom."], ["04", "DEPENDENCIES", "What states rely upon."], ["05", "STRATEGIC LEVERAGE", "Where systems combine to create influence."]];
const chokepoints = [["STRAIT OF MALACCA", "Maritime transit", "India · Indonesia · Malaysia · Singapore · China · Japan"], ["STRAIT OF HORMUZ", "Energy corridor", "Iran · Oman · Saudi Arabia · UAE · United States"], ["TURKISH STRAITS", "Maritime access", "Türkiye · Russia · Ukraine · NATO"], ["BAB-EL-MANDEB", "Maritime transit", "Yemen · Djibouti · Eritrea · Egypt"], ["SUEZ CANAL", "Global shipping", "Egypt · Europe · Asia · United States"], ["PANAMA CANAL", "Interoceanic route", "Panama · United States · East Asia"]];
const pressurePoints = ["INDO-PACIFIC", "HIMALAYAN FRONTIER", "TAIWAN STRAIT", "PERSIAN GULF", "RED SEA", "BLACK SEA", "EASTERN MEDITERRANEAN", "ARCTIC"];
const questions = ["Why does the Strait of Malacca matter to India?", "How can Russia influence India-China relations?", "What gives Türkiye leverage over Black Sea access?", "Compare India's and China's strategic positions.", "Which states are most exposed to Hormuz disruption?", "How does geography become geopolitical power?"];

function SectionLabel({ children }: { children: string }) { return <p className="section-kicker">TRINETRA / {children}</p>; }
function Coverage({ network }: { network: NetworkData | null }) { const types = useMemo(() => [...new Set(network?.edges.map((edge) => edge.type) ?? [])], [network]); return <div className="flex flex-wrap gap-x-8 gap-y-3 text-xs text-neutral-400"><span><strong className="font-display text-2xl text-white">{network?.nodes.length ?? "—"}</strong><span className="ml-2">states</span></span><span><strong className="font-display text-2xl text-white">{network?.edges.length ?? "—"}</strong><span className="ml-2">relationships</span></span><span><strong className="font-display text-2xl text-white">{types.length || "—"}</strong><span className="ml-2">relationship types</span></span></div>; }

export default function Dashboard() {
 const [network, setNetwork] = useState<NetworkData | null>(null); const [error, setError] = useState(false);
 const load = useCallback(() => { setError(false); api.getNetwork().then(setNetwork).catch(() => setError(true)); }, []); useEffect(() => { load(); }, [load]);
 return <div className="min-h-screen overflow-x-hidden bg-trinetra-bg text-neutral-200"><Header />
  <main>
   <section className="relative isolate min-h-[590px] overflow-hidden border-b border-trinetra-border"><div className="absolute inset-0 -z-10 bg-[url('/trinetra-earth.png')] bg-cover bg-[center_right] bg-no-repeat opacity-80" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-trinetra-bg via-trinetra-bg/90 to-transparent" /><div className="mx-auto flex min-h-[590px] w-full max-w-[1500px] items-center px-6 py-16 lg:px-12"><div className="max-w-xl"><SectionLabel>Strategic Intelligence</SectionLabel><h1 className="mt-5 max-w-lg font-display text-5xl leading-[.95] text-neutral-100 sm:text-7xl">See the world<br />as a strategic system.</h1><p className="mt-6 max-w-lg text-base leading-7 text-neutral-400">An evidence-led intelligence environment for understanding states, capabilities, geography, relationships, dependencies and strategic leverage.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#intelligence" className="flex items-center gap-2 rounded-sm bg-trinetra-saffron px-5 py-3 text-xs font-semibold uppercase tracking-wider text-black hover:bg-trinetra-saffronDim">Explore intelligence <ArrowRight data-icon="inline-end" /></a><a href="/analyze" className="flex items-center gap-2 rounded-sm border border-trinetra-saffron px-5 py-3 text-xs font-semibold uppercase tracking-wider text-trinetra-saffron hover:bg-trinetra-saffron hover:text-black">Ask Trinetra <ArrowUpRight data-icon="inline-end" /></a></div><div className="mt-12 border-t border-trinetra-border pt-5"><Coverage network={network} /></div></div></div></section>
   <section className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><SectionLabel>Intelligence Framework</SectionLabel><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><h2 className="font-display text-4xl text-white sm:text-5xl">Understand the system.</h2><p className="max-w-md text-sm leading-6 text-neutral-500">Trinetra connects the conditions beneath events to show where influence is created, constrained and transferred.</p></div><div className="mt-12 grid border-y border-trinetra-border sm:grid-cols-2 lg:grid-cols-5">{framework.map(([number, title, text]) => <div key={number} className="border-b border-trinetra-border px-0 py-6 sm:px-5 lg:border-b-0 lg:border-r lg:first:pl-0 lg:last:border-0"><span className="font-mono text-[10px] text-trinetra-saffron">{number}</span><h3 className="mt-8 font-display text-2xl text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-500">{text}</p></div>)}</div></section>
   <section id="intelligence" className="border-y border-trinetra-border bg-trinetra-panel/30"><div className="mx-auto max-w-[1500px] px-6 py-16 lg:px-12"><SectionLabel>Global Intelligence</SectionLabel><h2 className="mt-4 font-display text-4xl text-white sm:text-5xl">The world, in context.</h2><div className="mt-10 grid gap-8 lg:grid-cols-[.8fr_1.35fr_.8fr]"><div><p className="data-meta">Current signals</p><div className="mt-4 border-t border-trinetra-border">{["Diplomatic engagement continues", "Military developments under review", "Maritime security concerns persist", "Global energy volatility continues"].map((signal, i) => <div key={signal} className="border-b border-trinetra-border py-4"><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] text-trinetra-saffron">{["INDIA · CHINA", "RUSSIA · UKRAINE", "RED SEA", "ENERGY MARKETS"][i]}</span><span className="text-[10px] uppercase text-neutral-600">{i < 2 ? "Assessment" : "Monitoring"}</span></div><p className="mt-2 text-sm text-neutral-300">{signal}</p><p className="mt-1 text-xs text-neutral-600">Verified event detail unavailable</p></div>)}</div></div><div className="min-w-0"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="data-meta">Global system</p><span className="text-xs text-neutral-500">Select a nation to inspect ties</span></div>{error ? <div className="flex min-h-[370px] items-center justify-center border border-trinetra-border p-6" role="alert"><div className="text-center"><CircleAlert className="mx-auto text-trinetra-saffron" /><p className="mt-3 text-sm text-white">Relationship data unavailable</p><button onClick={load} className="mt-4 flex items-center gap-2 mx-auto text-xs text-trinetra-saffron"><RefreshCw data-icon="inline-start" /> Retry</button></div></div> : network ? <GlobalMap nodes={network.nodes} edges={network.edges} /> : <div className="flex min-h-[370px] items-center justify-center border border-trinetra-border text-sm text-neutral-500">Preparing geographic analysis…</div>}</div><div className="border-l border-trinetra-border pl-6"><p className="data-meta">Intelligence focus</p><div className="mt-4 border-t border-trinetra-border pt-8 text-center"><div className="mx-auto size-14 rounded-full border border-trinetra-saffron/70" /><p className="mt-5 font-display text-xl text-white">No selection</p><p className="mt-2 text-sm leading-6 text-neutral-500">Select a country or strategic node to inspect capabilities, dependencies and leverage.</p></div></div></div></div></section>
   <section className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><SectionLabel>Geographic Leverage</SectionLabel><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><h2 className="font-display text-4xl text-white sm:text-5xl">Where geography becomes power.</h2><a href="/network" className="text-xs uppercase tracking-wider text-trinetra-saffron">View all chokepoints <ArrowUpRight className="ml-1 inline" /></a></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{chokepoints.map(([name, type, actors], i) => <article key={name} className="group relative min-h-56 overflow-hidden border border-trinetra-border"><div className="absolute inset-0 bg-[url('/chokepoints-atlas.png')] bg-cover opacity-45 transition-opacity group-hover:opacity-65" style={{ backgroundPosition: `${(i % 3) * 50}% ${i > 2 ? 100 : 0}%` }} /><div className="absolute inset-0 bg-gradient-to-t from-trinetra-bg via-trinetra-bg/70 to-transparent" /><div className="relative flex h-full min-h-56 flex-col justify-end p-5"><span className="data-meta text-trinetra-saffron">{type}</span><h3 className="mt-2 font-display text-2xl text-white">{name}</h3><p className="mt-3 text-xs leading-5 text-neutral-400"><span className="text-neutral-600">Relevant states: </span>{actors}</p><p className="mt-3 border-t border-white/10 pt-3 text-xs text-neutral-500">Mechanism of leverage · access, proximity, dependency and constraint</p></div></article>)}</div></section>
   <section className="border-y border-trinetra-border bg-trinetra-panel/20"><div className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><SectionLabel>Country Intelligence</SectionLabel><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><h2 className="font-display text-4xl text-white sm:text-5xl">States are not just numbers.</h2><a href="/countries" className="text-xs uppercase tracking-wider text-trinetra-saffron">Open country intelligence <ArrowUpRight className="ml-1 inline" /></a></div><div className="mt-10 grid gap-8 lg:grid-cols-3"><div className="border-t border-trinetra-border pt-5"><p className="data-meta">Capability</p><p className="mt-3 text-sm leading-6 text-neutral-400">Military, economic, technological and energy capacity in context—not reduced to an arbitrary power score.</p></div><div className="border-t border-trinetra-border pt-5"><p className="data-meta">Geography</p><p className="mt-3 text-sm leading-6 text-neutral-400">Position, access, routes, terrain and proximity shape what states can influence.</p></div><div className="border-t border-trinetra-border pt-5"><p className="data-meta">Vulnerability</p><p className="mt-3 text-sm leading-6 text-neutral-400">Dependencies and constraints expose where strategic pressure can accumulate.</p></div></div></div></section>
   <section className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><div className="grid gap-14 lg:grid-cols-2"><div><SectionLabel>Relationships</SectionLabel><h2 className="mt-4 font-display text-4xl text-white sm:text-5xl">Who affects whom?</h2><p className="mt-5 max-w-lg text-sm leading-7 text-neutral-500">Important relationships are more useful than an unreadable spider-web. Explore defence, energy, trade, diplomacy, rivalries and partnerships through the network.</p><a href="/network" className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-wider text-trinetra-saffron">Open relationship network <ArrowRight data-icon="inline-end" /></a></div><div><SectionLabel>Dependencies</SectionLabel><h2 className="mt-4 font-display text-4xl text-white sm:text-5xl">The world runs on dependencies.</h2><div className="mt-6 flex flex-wrap gap-2">{["ENERGY", "TRADE", "TECHNOLOGY", "CRITICAL MINERALS", "FOOD", "MARITIME ROUTES", "DEFENCE SUPPLY", "FINANCE"].map((item) => <span key={item} className="border border-trinetra-border px-3 py-2 font-mono text-[10px] text-neutral-400">{item}</span>)}</div></div></div></section>
   <section className="border-y border-trinetra-border bg-trinetra-panel/20"><div className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><SectionLabel>Anticipate</SectionLabel><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><h2 className="font-display text-4xl text-white sm:text-5xl">Where pressure builds.</h2><span className="data-meta">Fact · Assessment · Confidence</span></div><div className="mt-10 grid grid-cols-2 gap-px border border-trinetra-border bg-trinetra-border sm:grid-cols-4">{pressurePoints.map((point, i) => <div key={point} className="min-h-28 bg-trinetra-bg p-4"><span className="data-meta">0{i + 1}</span><h3 className="mt-5 text-xs font-medium text-white">{point}</h3><p className="mt-2 text-[11px] text-neutral-600">{i < 5 ? "Monitoring" : "Data pending"}</p></div>)}</div></div></section>
   <section className="mx-auto max-w-[1500px] px-6 py-20 lg:px-12"><div className="max-w-3xl"><SectionLabel>Ask Trinetra</SectionLabel><h2 className="mt-4 font-display text-4xl text-white sm:text-6xl">Turn geopolitical complexity into an understandable strategic picture.</h2><a href="/analyze" className="mt-8 inline-flex items-center gap-2 rounded-sm bg-trinetra-saffron px-5 py-3 text-xs font-semibold uppercase tracking-wider text-black">Open intelligence analysis <ArrowRight data-icon="inline-end" /></a></div><div className="mt-12 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{questions.map((question) => <a href="/analyze" key={question} className="border border-trinetra-border p-4 text-sm text-neutral-400 transition-colors hover:border-trinetra-saffron hover:text-white">{question}<ArrowUpRight className="float-right text-trinetra-saffron" /></a>)}</div></section>
  </main><Footer /></div>;
}
