import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Header from "../components/dashboard/Header";
import Footer from "../components/dashboard/Footer";
import { STRATEGIC_GROUPS, type StrategicGroup } from "../data/strategicGroups";
import { api } from "../services/api";
import type { CountryIndexEntry } from "../types";

const FLAGS: Record<string, string> = { IND:"🇮🇳", CHN:"🇨🇳", USA:"🇺🇸", RUS:"🇷🇺", JPN:"🇯🇵", GBR:"🇬🇧", FRA:"🇫🇷", DEU:"🇩🇪", KOR:"🇰🇷", TUR:"🇹🇷", SAU:"🇸🇦", IRN:"🇮🇷", ISR:"🇮🇱", PAK:"🇵🇰", AUS:"🇦🇺", CAN:"🇨🇦", BRA:"🇧🇷", IDN:"🇮🇩", ITA:"🇮🇹", ARE:"🇦🇪", BGD:"🇧🇩", ZAF:"🇿🇦", EGY:"🇪🇬", ETH:"🇪🇹", KAZ:"🇰🇿", KGZ:"🇰🇬", TJK:"🇹🇯", UZB:"🇺🇿", BLR:"🇧🇾" };
const GROUP_ART: Record<string, string> = { g20:"/trinetra-earth.png", g7:"/chokepoints-atlas.png", brics:"/trinetra-earth.png", sco:"/chokepoints-atlas.png", quad:"/trinetra-earth.png" };

export default function Groups() {
  const [countries, setCountries] = useState<CountryIndexEntry[]>([]);
  const [selected, setSelected] = useState("g20");
  useEffect(() => { const c = new AbortController(); api.getCountries(c.signal).then(setCountries).catch(() => setCountries([])); return () => c.abort(); }, []);
  const available = useMemo(() => new Set(countries.map((c) => c.id)), [countries]);
  const group = STRATEGIC_GROUPS.find((g) => g.id === selected) || STRATEGIC_GROUPS[0];
  const memberName = (id: string) => countries.find((c) => c.id === id)?.name || id;
  return <div className="min-h-screen bg-trinetra-bg text-neutral-200"><Header /><main className="mx-auto max-w-[1500px] px-5 py-10 lg:px-10">
    <div className="mb-10 max-w-4xl"><p className="section-kicker">STRATEGIC GROUPINGS / VISUAL INTELLIGENCE</p><h1 className="mt-3 font-display text-5xl text-white md:text-7xl">The world is organized through relationships.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-neutral-400">Explore G20, G7, BRICS, SCO and QUAD through membership, geography, economic ties, security interests and available evidence. A grouping is a context—not a single unified position.</p></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{STRATEGIC_GROUPS.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} aria-pressed={selected === item.id} className={`group relative min-h-44 overflow-hidden border text-left transition-all ${selected === item.id ? "border-trinetra-saffron" : "border-trinetra-border hover:border-trinetra-saffron/60"}`}><img src={GROUP_ART[item.id]} alt="" className="absolute inset-0 h-full w-full object-cover opacity-25 transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/70 to-black/10" /><div className="relative flex h-full flex-col justify-between p-5"><span className="font-mono text-[10px] tracking-[.2em] text-trinetra-saffron">{item.id.toUpperCase()}</span><div><h2 className="font-display text-4xl text-white">{item.name}</h2><p className="mt-2 text-xs text-neutral-400">{item.members.length} listed members</p></div></div></button>)}</div>
    <section className="mt-8 border border-trinetra-border bg-trinetra-panel/50"><div className="grid gap-0 lg:grid-cols-[1.1fr_1fr]"><div className="relative min-h-[360px] overflow-hidden border-b border-trinetra-border lg:border-b-0 lg:border-r"><img src={GROUP_ART[group.id]} alt={`${group.name} strategic visual`} className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/50 to-transparent" /><div className="relative flex min-h-[360px] flex-col justify-end p-7 md:p-10"><p className="section-kicker">SELECTED GROUP</p><h2 className="mt-2 font-display text-6xl text-white">{group.name}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-neutral-300">{group.description}</p><div className="mt-5 flex flex-wrap gap-2">{group.focusAreas.map((area) => <span key={area} className="border border-white/15 bg-black/30 px-3 py-2 text-[10px] uppercase tracking-wider text-neutral-300">{area}</span>)}</div></div></div>
      <div className="p-7 md:p-10"><div className="flex items-end justify-between gap-4"><div><p className="section-kicker">MEMBERSHIP / COVERAGE</p><h3 className="mt-2 font-display text-3xl text-white">Member countries</h3></div><span className="font-mono text-xs text-neutral-500">{group.members.filter((id) => available.has(id)).length}/{group.members.length} covered</span></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{group.members.map((id) => <Link key={id} to={available.has(id) ? `/country?id=${id}` : "#"} onClick={(event) => { if (!available.has(id)) event.preventDefault(); }} className={`flex min-h-20 flex-col justify-between border p-3 transition-colors ${available.has(id) ? "border-trinetra-border bg-black/20 hover:border-trinetra-saffron" : "border-dashed border-neutral-800 opacity-55"}`}><span className="text-2xl">{FLAGS[id] || "🌐"}</span><span className="text-xs text-white">{memberName(id)}</span><span className="font-mono text-[9px] uppercase tracking-wider text-neutral-500">{available.has(id) ? "Profile available" : "Data unavailable"}</span></Link>)}</div><p className="mt-5 text-xs leading-5 text-neutral-500">Coverage reflects the countries and evidence currently available in Trinetra AI. Missing members are not assigned invented metrics.</p></div></div></section>
    <div className="mt-8 border border-trinetra-border bg-black/20 p-5 text-sm text-neutral-400">Explore the underlying country records in <Link className="text-trinetra-saffron hover:underline" to="/countries">Country Intelligence →</Link></div>
  </main><Footer /></div>;
}
