// TRINETRA AI — Sovereign Country Command Header
// Universal 3-Box Architecture matching the reference visual:
// [LEFT: Country Visual & Flag] [CENTER: Sovereign Identity & Doctrine] [RIGHT: Strategic Theater Mini-Map]
import React, { useState } from "react";
import {
  MapPin,
  Globe2,
  Landmark,
  Radiation,
  Download,
  Swords,
  ChevronRight,
  ShieldCheck,
  Check,
} from "lucide-react";
import type { Country } from "../../types";
import type { CountryDeepProfile } from "../../data/countryDeepProfileData";
import { getCountryFlashCardDossier } from "../../data/countryFlashCardData";
import { HeaderMiniMap } from "./HeaderMiniMap";

interface CountryCommandHeaderProps {
  country: Country;
  deepProfile?: CountryDeepProfile;
  audioPlaying?: boolean;
  audioAvailable?: boolean;
  onToggleAudio?: () => void;
  onOpenCompare?: () => void;
  onCompare?: () => void;
  onOpenFullMap?: () => void;
  onNavigateHome?: () => void;
}

export const CountryCommandHeader: React.FC<CountryCommandHeaderProps> = ({
  country,
  deepProfile,
  onOpenCompare,
  onCompare,
  onOpenFullMap,
  onNavigateHome,
}) => {
  const handleCompare = onOpenCompare || onCompare || (() => {});
  const flashDossier = getCountryFlashCardDossier(country.id, country, deepProfile);
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  // Download dossier simulation
  const handleDownloadDossier = () => {
    setDownloading(true);
    setTimeout(() => {
      setDownloading(false);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
      
      // Generate clean factual dossier text file
      const blob = new Blob([
        `TRINETRA AI — SOVEREIGN INTELLIGENCE DOSSIER: ${country.name.toUpperCase()} [${country.id}]\n` +
        `Official Name: ${flashDossier.officialName}\n` +
        `Capital: ${flashDossier.capital}\n` +
        `Region: ${flashDossier.region}\n` +
        `Doctrine: ${flashDossier.doctrineQuote}\n\n` +
        `EXECUTIVE SUMMARY:\n${flashDossier.narrativeSummary}\n\n` +
        `KEY METRICS:\n` +
        flashDossier.topMetrics.map(m => `- ${m.label}: ${m.value} (${m.source}, ${m.year})`).join('\n') +
        `\n\nGenerated by TRINETRA AI Sovereign Geospatial Intelligence Platform.`
      ], { type: "text/plain;charset=utf-8" });
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `TRINETRA_${country.id}_INTELLIGENCE_DOSSIER.txt`;
      link.click();
      URL.revokeObjectURL(url);
    }, 600);
  };

  const isNuclear = country.nuclear?.weapons_state || deepProfile?.nuclear?.status?.toLowerCase().includes("weapon");

  return (
    <div className="mb-6">
      {/* Top Breadcrumb Navigation */}
      <div className="flex items-center gap-2 text-xs font-mono text-neutral-400 mb-3">
        <button
          type="button"
          onClick={onNavigateHome}
          className="hover:text-white transition-colors cursor-pointer"
        >
          Countries
        </button>
        <ChevronRight className="size-3 text-neutral-600" />
        <span className="text-trinetra-saffron font-medium">{country.name}</span>
        <span className="text-neutral-600">·</span>
        <span className="text-neutral-500 uppercase">Sovereign Dossier</span>
      </div>

      {/* 3-Box Command Header Grid */}
      <div className="rounded-2xl border border-white/10 bg-[#07090e] p-3 sm:p-4 lg:p-5 shadow-2xl">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-5 items-stretch">
          
          {/* BOX 1: Left Country Visual & Flag (3 cols) */}
          <div className="lg:col-span-3 flex flex-col justify-center">
            <div className="relative w-full h-[220px] sm:h-[260px] lg:h-full min-h-[220px] rounded-xl overflow-hidden border border-white/10 group shadow-inner">
              <img
                src={flashDossier.heroImage}
                alt={country.name}
                className="w-full h-full object-cover object-center filter brightness-[0.8] contrast-110 group-hover:scale-105 transition-transform duration-700"
                referrerPolicy="no-referrer"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent" />
              
              {/* Flag Badge & Country ID in corner */}
              <div className="absolute top-3 left-3 flex items-center gap-2 px-2.5 py-1 rounded-md bg-black/80 border border-white/15 backdrop-blur-xs">
                <span className="text-base" role="img" aria-label="Flag">
                  {flashDossier.flag}
                </span>
                <span className="font-mono text-xs font-bold text-white tracking-widest">
                  {country.id}
                </span>
              </div>

              {/* Bottom Image Tag */}
              <div className="absolute bottom-2.5 left-3 right-3 text-left">
                <span className="text-[10px] font-mono text-neutral-400 uppercase tracking-widest block">
                  SOVEREIGN TERRITORY
                </span>
                <span className="text-xs font-semibold text-white truncate block">
                  {flashDossier.capital}, {country.name}
                </span>
              </div>
            </div>
          </div>

          {/* BOX 2: Center Sovereign Identity & Doctrine (6 cols) */}
          <div className="lg:col-span-6 flex flex-col justify-between py-1">
            <div>
              {/* Title & ISO Badge */}
              <div className="flex flex-wrap items-center gap-2.5 mb-1.5">
                <h1 className="font-display text-3xl sm:text-4xl lg:text-5xl font-bold text-white tracking-tight">
                  {country.name}
                </h1>
                <span className="font-mono text-xs font-bold px-2.5 py-0.5 rounded bg-trinetra-saffron/15 border border-trinetra-saffron/40 text-trinetra-saffron uppercase">
                  {country.id}
                </span>
              </div>

              {/* Official Name */}
              <p className="text-xs sm:text-sm font-mono text-neutral-400 mb-3">
                {flashDossier.officialName}
              </p>

              {/* 4 Metadata Pills Row with Icons */}
              <div className="flex flex-wrap items-center gap-2 mb-4">
                <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-[#0e121a] border border-white/8 text-xs text-neutral-300">
                  <MapPin className="size-3.5 text-trinetra-saffron shrink-0" />
                  <span>{flashDossier.capital}</span>
                </div>
                <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-[#0e121a] border border-white/8 text-xs text-neutral-300">
                  <Globe2 className="size-3.5 text-sky-400 shrink-0" />
                  <span>{flashDossier.region}</span>
                </div>
                <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-[#0e121a] border border-white/8 text-xs text-neutral-300">
                  <Landmark className="size-3.5 text-amber-400 shrink-0" />
                  <span className="truncate max-w-[180px]">{deepProfile?.leadership?.systemType || (country as any)?.politics?.system || "Constitutional State"}</span>
                </div>
                {isNuclear && (
                  <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-rose-950/40 border border-rose-500/30 text-xs text-rose-300">
                    <Radiation className="size-3.5 text-rose-400 shrink-0 animate-pulse" />
                    <span>Declared Nuclear Deterrent</span>
                  </div>
                )}
              </div>

              {/* Doctrine Quote */}
              <div className="mb-3 px-3 py-2 rounded-lg bg-white/[0.02] border-l-2 border-trinetra-saffron">
                <p className="text-xs sm:text-sm font-serif italic text-white/90">
                  {flashDossier.doctrineQuote}
                </p>
              </div>

              {/* Narrative Summary */}
              <p className="text-xs sm:text-sm text-neutral-400 leading-relaxed line-clamp-3">
                {flashDossier.narrativeSummary}
              </p>
            </div>

            {/* 3 Action Buttons */}
            <div className="flex flex-wrap items-center gap-2.5 mt-5 pt-3 border-t border-white/5">
              <button
                type="button"
                onClick={handleDownloadDossier}
                disabled={downloading}
                className="flex items-center gap-2 px-3.5 py-2 rounded-lg bg-trinetra-saffron hover:bg-orange-600 text-black font-semibold text-xs transition-all shadow-md cursor-pointer disabled:opacity-50"
              >
                {downloaded ? (
                  <>
                    <Check className="size-3.5" />
                    <span>Dossier Ready</span>
                  </>
                ) : downloading ? (
                  <>
                    <span className="size-3.5 border-2 border-black border-t-transparent rounded-full animate-spin" />
                    <span>Exporting...</span>
                  </>
                ) : (
                  <>
                    <Download className="size-3.5" />
                    <span>Download Dossier</span>
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={handleCompare}
                className="flex items-center gap-2 px-3.5 py-2 rounded-lg bg-[#0e121a] hover:bg-[#141a24] border border-white/10 hover:border-white/20 text-neutral-200 hover:text-white font-medium text-xs transition-colors cursor-pointer"
              >
                <Swords className="size-3.5 text-trinetra-saffron" />
                <span>Compare</span>
              </button>

              {onOpenFullMap && (
                <button
                  type="button"
                  onClick={onOpenFullMap}
                  className="flex items-center gap-2 px-3.5 py-2 rounded-lg bg-[#0e121a] hover:bg-[#141a24] border border-white/10 hover:border-white/20 text-neutral-200 hover:text-white font-medium text-xs transition-colors cursor-pointer"
                >
                  <MapPin className="size-3.5 text-sky-400" />
                  <span>View on Map</span>
                </button>
              )}
            </div>
          </div>

          {/* BOX 3: Right Strategic Geographic Map (3 cols) */}
          <div className="lg:col-span-3 flex flex-col justify-center">
            <HeaderMiniMap
              countryId={country.id}
              countryName={country.name}
              onOpenFullMap={onOpenFullMap}
            />
          </div>

        </div>
      </div>
    </div>
  );
};
